import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
const sidebars: SidebarsConfig = {
  blogSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default sidebars;
